language: c
os:
  - linux
  - osx
env:
  - OCAML_VERSION=4.03 INSTALL_XQUARTZ=false
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - ./configure
  - make
  - sudo make install
script:
  - cd test
  - omake
